### ISSUE TITLE
Can we update file server by simply changing the binary file?

### ISSUE THREAD

**Issue by SydneyOwl** [ngxson/hobby-kindle-http-file-server#2]
There're some shell scripts used to start the binary file in the release, and the binary comes from [filebrowser_github](https://github.com/filebrowser/filebrowser), just as you said. So is it possible to update kindle server by changing original `filebrowser`  to the one download from the website mentioned above?

**Comment by ngxson** [comment]
In theory, that should work.
However, I haven't tested newer version. I'm not sure about the compatibility.
